scrape_configs:
  - job_name: 'exporter'
    static_configs:
      - targets: ['exporter:8080']

global:
  scrape_interval: 5s
  evaluation_interval: 5s
  scrape_timeout: 5s

alerting:
 alertmanagers:
   - static_configs:
     - targets:
       - alertmanager:9093

rule_files:
  - "alert.rules"
